### ISSUE TITLE
Create data class for ephemeris service

### ISSUE THREAD

**Issue by mschwamb** [lsst-sssc/ssoforcedphot#4]
Proposed data class structure:
<img width="1110" alt="Screenshot 2024-06-26 at 1 24 22 AM" src="https://github.com/lsst-sssc/ssoforcedphot/assets/753325/99ba0bcb-cf71-43d3-be2b-a03b047f19e5">

Changes to the approve proposed structure was to add units to the names, treat everything as numpy arrays of floats, and use the astropy time class for the time variables. 

subclasses for JPL Horizons, skybot, and manual ingestion of the data (csv file and manually sending to an init function/constructor) are needed

**Comment by szilac** [comment]
![ephem_dataclass_screenshot](https://github.com/lsst-sssc/ssoforcedphot/assets/6682143/95a7977b-5289-47b6-8215-7b5a6c51c5b1)

I have made the requested changes. Currently working on the SkyBot (Miriade) interface and the unit tests.
